[package]
name = "ima"
version = "0.1.0"
edition = "2021"
authors = ["Virgile HENRY <virgile.henry@grenoble-inp.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ima-core = { path = "../ima-core" }